import re
import math
from typing import List, Dict, Any

# A rich set of hospital documentation, policies, FAQs, and procedures
DOCUMENTS = [
    {
        "id": "opd_guidelines",
        "category": "OPD & Services",
        "title": "OPD Timings, Fees, and Specialist Departments",
        "content": "Bharat Health Care Out-Patient Department (OPD) timings are from 9:00 AM to 5:00 PM, Monday to Saturday. The registration counter closes at 4:30 PM. The consultation fee is ₹300 for General Medicine and ₹500 for specialist consults (Cardiology, Neurology, Pediatrics, and Orthopedics). Emergency services, casualty, and trauma care are available 24/7, located on the Ground Floor, Wing A."
    },
    {
        "id": "appointment_policy",
        "category": "Appointments",
        "title": "Appointment Booking, Rescheduling, and Cancellation Policy",
        "content": "Appointments can be booked up to 30 days in advance. Patients can reschedule or cancel appointments online or via the AI assistant up to 2 hours before the scheduled time slot. Once cancelled, the slot is immediately released for other patients. If a patient is late by more than 15 minutes, their slot might be cancelled, requiring a fresh booking."
    },
    {
        "id": "billing_refunds",
        "category": "Billing",
        "title": "Billing Lifecycle, Verification, Payments, and Refunds",
        "content": "All bills generated by doctor sessions or lab tests are initially marked as 'pending'. They must be verified by the Admin billing staff before a payment is processed. Verified bills can be paid online via UPI (Google Pay, PhonePe, Paytm), credit/debit card, or cash at the counter. Refunds for cancelled paid appointments or duplicate billing are automatically refunded to the source account within 3 to 5 business days."
    },
    {
        "id": "reports_lab",
        "category": "Lab & Reports",
        "title": "Lab Tests, Scans, and Medical Reports Processing Time",
        "content": "Diagnostic reports for standard blood tests, sugar levels, and urine tests are uploaded to the Patient Portal within 12 hours. Advanced scans like MRI, CT Scans, and Ultrasound take up to 24 hours to generate. X-ray scans are usually available within 4 hours. In emergency/casualty cases, all scan reports are expedited and made available within 1-2 hours."
    },
    {
        "id": "mri_prep",
        "category": "Clinical Prep",
        "title": "Preparation Guidelines for MRI and CT Scans",
        "content": "For an MRI scan, patients must remove all metal accessories, jewelry, hairpins, and keys. Patients with cardiac pacemakers, metallic implants, or artificial heart valves must inform the radiologist beforehand. For abdominal CT scans, fasting of 4-6 hours is required, and patients may need to drink a contrast medium solution supplied by the lab 1 hour before the scan."
    },
    {
        "id": "blood_prep",
        "category": "Clinical Prep",
        "title": "Fasting Requirements for Blood Sugar and Lipid Profile Tests",
        "content": "Fasting Blood Sugar (FBS) and Lipid Profile tests require a strict fasting period of 8 to 12 hours. Patients should not consume any food or beverages except plain water during this period. Routine morning medications can be taken with water unless instructed otherwise by the physician. Diabetic patients should check with their doctor regarding insulin dosage during fasting."
    },
    {
        "id": "cardio_dept",
        "category": "Departments",
        "title": "Cardiology Department & Heart Care Services",
        "content": "The Cardiology Department at Bharat Health Care provides comprehensive heart care services led by chief consultant Dr. Bishal Ranjan Das. Key procedures include Electrocardiogram (ECG), Echocardiography (2D Echo), Holter Monitoring, Coronary Angiography, and Angioplasty. The department is open for outpatient consultations from 9:00 AM to 5:00 PM (Monday-Saturday) in Wing C, First Floor."
    },
    {
        "id": "neuro_dept",
        "category": "Departments",
        "title": "Neurology and Brain Care Unit",
        "content": "The Neurology Department specializes in treating brain, spine, nerve, and muscle disorders including stroke, epilepsy, epilepsy management, migraines, dementia, and Parkinson's disease. The clinic has advanced Electroencephalogram (EEG) and Nerve Conduction Velocity (NCV) test beds, open Monday to Saturday. Located in Wing B, Second Floor."
    },
    {
        "id": "pedia_dept",
        "category": "Departments",
        "title": "Pediatrics and Child Health Care",
        "content": "The Pediatrics Department is a child-friendly medical facility catering to infants, children, and adolescents. Services include routine immunizations, child growth monitoring, pediatric emergency care, and nutritional counseling. Open daily from 9:00 AM to 5:00 PM. Located in Wing D, Ground Floor."
    },
    {
        "id": "ortho_dept",
        "category": "Departments",
        "title": "Orthopedics and Joint Care Center",
        "content": "The Orthopedics division treats bone fractures, joint replacements (hip and knee), sports injuries, arthritis, back pain, and spinal disorders. Our state-of-the-art physiotherapy gym is available for post-operative rehabilitation. Consultations are available daily. Located in Wing C, Ground Floor."
    }
]

def clean_text(text: str) -> str:
    """Helper to tokenize and clean text."""
    return re.sub(r'[^a-zA-Z0-9\s]', '', text.lower().strip())

def search_documents(query: str, top_k: int = 3) -> List[Dict[str, Any]]:
    """
    Search hospital policies, FAQs, and documentation using an optimized,
    weighted TF-IDF score over keywords, matching phrases, and token overlap.
    """
    cleaned_query = clean_text(query)
    query_words = [w for w in cleaned_query.split() if len(w) > 2]
    
    if not query_words:
        # Fallback if query is too short
        return DOCUMENTS[:top_k]
        
    scored_docs = []
    
    for doc in DOCUMENTS:
        doc_text = clean_text(f"{doc['title']} {doc['category']} {doc['content']}")
        score = 0.0
        
        # 1. Exact phrase matching bonus
        if cleaned_query in doc_text:
            score += 15.0
            
        # 2. Key term frequency score
        for word in query_words:
            matches = len(re.findall(r'\b' + re.escape(word) + r'\b', doc_text))
            if matches > 0:
                # Add word matching weight
                score += (matches * 2.0)
                # Title weight multiplier
                title_clean = clean_text(doc['title'])
                if word in title_clean:
                    score += 5.0
                    
        if score > 0:
            scored_docs.append((score, doc))
            
    # Sort by descending score
    scored_docs.sort(key=lambda x: x[0], reverse=True)
    
    results = []
    for score, doc in scored_docs[:top_k]:
        results.append({
            "id": doc["id"],
            "title": doc["title"],
            "category": doc["category"],
            "content": doc["content"],
            "score": round(score, 2)
        })
        
    # If no matches, return a default helpful context set
    if not results:
        return [
            {
                "id": doc["id"],
                "title": doc["title"],
                "category": doc["category"],
                "content": doc["content"],
                "score": 0.0
            } for doc in DOCUMENTS[:top_k]
        ]
        
    return results

def get_rag_context(query: str) -> str:
    """
    Fetches matching docs and formats them into a structured RAG block 
    suitable for immediate system prompt injection.
    """
    matches = search_documents(query, top_k=2)
    context_str = "\n=== CLINICAL POLICIES & HOSPITAL RAG FAQ DATA ===\n"
    for doc in matches:
        context_str += f"[{doc['category']}] {doc['title']}:\n{doc['content']}\n\n"
    return context_str
